# Generated by Django 4.2 on 2023-06-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_orderrprodeuct_orderproduct_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='item',
            new_name='items',
        ),
    ]
