# Generated by Django 4.2 on 2023-06-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_item_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
